// Generated by CoffeeScript 1.6.3
(function() {
  var ModelStream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = ModelStream = (function(_super) {
    __extends(ModelStream, _super);

    function ModelStream(model_type, query) {
      this.model_type = model_type;
      this.query = query != null ? query : {};
      ModelStream.__super__.constructor.call(this, {
        objectMode: true
      });
      this.ended = false;
    }

    ModelStream.prototype._read = function() {
      var done,
        _this = this;
      if (this.ended) {
        return;
      }
      done = function(err) {
        _this.ended = true;
        if (err) {
          _this.emit('error', err);
        }
        return _this.push(null);
      };
      return this.model_type.batch(this.query, {}, done, function(model, callback) {
        _this.push(model);
        return callback();
      });
    };

    return ModelStream;

  })(require('stream').Readable);

}).call(this);
