// Generated by CoffeeScript 1.6.3
(function() {
  var Backbone, Utils, _original__prepareModel;

  Backbone = require('backbone');

  Utils = require('../utils');

  _original__prepareModel = Backbone.Collection.prototype._prepareModel;

  Backbone.Collection.prototype._prepareModel = function(attrs, options) {
    var id, is_new, model;
    if (!Utils.isModel(attrs) && (id = Utils.dataId(attrs))) {
      if (this.model.cache) {
        is_new = !!this.model.cache.get(id);
      }
      model = Utils.updateOrNew(attrs, this.model);
      if (is_new && !model._validate(attrs, options)) {
        this.trigger('invalid', this, attrs, options);
        return false;
      }
      return model;
    }
    return _original__prepareModel.call(this, attrs, options);
  };

}).call(this);
