// Generated by CoffeeScript 1.7.1
(function() {
  var BackboneORM, exports, root;

  BackboneORM = typeof window !== "undefined" && window !== null ? window.BackboneORM : void 0;

  try {
    BackboneORM || (BackboneORM = typeof require === "function" ? require('backbone-orm') : void 0);
  } catch (_error) {

  }

  try {
    BackboneORM || (BackboneORM = typeof require === "function" ? require('../backbone-orm') : void 0);
  } catch (_error) {}

  exports = {
    sync: BackboneORM.sync
  };

  (root = typeof window !== "undefined" && window !== null ? window : global).__test__parameters = exports;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = exports;
  }

  return exports;

}).call(this);
