// Generated by CoffeeScript 1.6.3
/*
  backbone-orm.js 0.0.1
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-orm
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Dependencies: Backbone.js and Underscore.js.
*/


(function() {
  var ClientUtils, isArray;

  isArray = require('../node/util').isArray;

  module.exports = ClientUtils = (function() {
    function ClientUtils() {}

    ClientUtils.loadDependencies = function(info) {
      var item, _fn, _i, _len;
      if (!(typeof window !== "undefined" && window !== null ? window.require.register : void 0)) {
        return;
      }
      if (!isArray(info)) {
        info = [info];
      }
      _fn = function(item) {
        var dep, err;
        try {
          if (dep = require(item.path)) {
            return;
          }
        } catch (_error) {
          err = _error;
        }
        if (!(dep = this[item.symbol])) {
          if (item.optional) {
            return;
          }
          throw new Error("Missing dependency: " + item.path);
        }
        return window.require.register(item.path, function(exports, require, module) {
          return module.exports = dep;
        });
      };
      for (_i = 0, _len = info.length; _i < _len; _i++) {
        item = info[_i];
        _fn(item);
      }
    };

    return ClientUtils;

  })();

}).call(this);
