// Generated by CoffeeScript 1.6.3
/*
  backbone-orm.js 0.0.1
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-orm
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Dependencies: Backbone.js and Underscore.js.
*/


(function() {
  var ClientUtils;

  module.exports = ClientUtils = (function() {
    function ClientUtils() {}

    ClientUtils.loadDependency = function(item) {
      var components, dep, err, key, path, _i, _j, _len, _len1, _ref;
      if (typeof window === "undefined" || window === null) {
        return;
      }
      try {
        if (require(item.path)) {
          return;
        }
      } catch (_error) {
        err = _error;
      }
      try {
        dep = typeof window.require === "function" ? window.require(item.path) : void 0;
      } catch (_error) {
        err = _error;
      }
      if (!dep && item.symbol) {
        dep = window;
        _ref = item.symbol.split('.');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          if (!(dep = dep[key])) {
            break;
          }
        }
      }
      if (!dep && item.symbol_path && window.require) {
        components = item.symbol_path.split('.');
        path = components.shift();
        try {
          dep = typeof window.require === "function" ? window.require(path) : void 0;
        } catch (_error) {
          err = _error;
        }
        for (_j = 0, _len1 = components.length; _j < _len1; _j++) {
          key = components[_j];
          if (!(dep = dep != null ? dep[key] : void 0)) {
            break;
          }
        }
      }
      if (!dep) {
        if (item.optional) {
          return;
        }
        throw new Error("Missing dependency: " + item.path);
      }
      require.register(item.path, (function(exports, require, module) {
        return module.exports = dep;
      }));
      if (item.alias) {
        return require.register(item.alias, (function(exports, require, module) {
          return module.exports = dep;
        }));
      }
    };

    ClientUtils.loadDependencies = function(info) {
      var item, _i, _len;
      for (_i = 0, _len = info.length; _i < _len; _i++) {
        item = info[_i];
        this.loadDependency(item);
      }
    };

    return ClientUtils;

  })();

}).call(this);
