// Generated by CoffeeScript 1.6.3
/*
  backbone-orm.js 0.5.0
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-orm
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Dependencies: Backbone.js and Underscore.js.
*/


(function() {
  var MemoryStore;

  MemoryStore = require('./cache/memory_store');

  module.exports = new MemoryStore({
    destroy: function(url, connection) {
      return connection.destroy();
    }
  });

}).call(this);
