// Generated by CoffeeScript 1.6.3
(function() {
  var MemoryStore;

  MemoryStore = require('./cache/memory_store');

  module.exports = new MemoryStore({
    destroy: function(url, connection) {
      return connection.destroy();
    }
  });

}).call(this);
