// Generated by CoffeeScript 1.6.3
/*
  backbone-orm.js 0.0.1
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-orm
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Dependencies: Backbone.js and Underscore.js.
*/


(function() {
  var ModelTypeID, crypto, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  crypto = require('crypto');

  module.exports = ModelTypeID = (function() {
    function ModelTypeID() {
      this.generate = __bind(this.generate, this);
      this.modelID = __bind(this.modelID, this);
      this.reset = __bind(this.reset, this);
      this.ids = {};
    }

    ModelTypeID.prototype.reset = function() {
      return this.ids = {};
    };

    ModelTypeID.prototype.modelID = function(model_type) {
      var name_url;
      name_url = "" + (_.result(model_type.prototype, 'url')) + "_" + model_type.model_name;
      return crypto.createHash('md5').update(name_url).digest('hex');
    };

    ModelTypeID.prototype.generate = function(model_type) {
      var id;
      id = this.modelID(model_type);
      if (this.ids[id] && this.ids[id] !== model_type) {
        throw new Error("Duplicate model name / url combination: " + model_type.model_name + ", " + (_.result(model_type.prototype, 'url')) + ". Set a unique model_name property on one of the conflicting models.");
      }
      this.ids[id] = model_type;
      return id;
    };

    return ModelTypeID;

  })();

}).call(this);
