// Generated by CoffeeScript 1.6.3
/*
  backbone-orm.js 0.0.1
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-orm
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Dependencies: Backbone.js and Underscore.js.
*/


(function() {
  module.exports = {
    ModelCache: new (require('./model_cache'))(),
    QueryCache: new (require('./query_cache'))()
  };

}).call(this);
